import mongoose, { Document, Schema } from 'mongoose';

export type AssetKind = 'template' | 'source' | 'export-docx' | 'export-pdf';

/**
 * @interface IAsset
 * @extends {Document}
 * @description Represents a physical file (PDF, DOCX, image, etc.) uploaded by a user or generated by the AI, stored in an external bucket (S3/GCS).
 */
export interface IAsset extends Document {
  /** The user who uploaded or generated this asset */
  owner: mongoose.Types.ObjectId;
  /** The specific project workspace this asset belongs to (optional for global templates) */
  project?: mongoose.Types.ObjectId;
  /** The unique storage key (e.g., S3 object key) used to retrieve the actual file */
  key: string;
  /** Categorizes the file's purpose within the system */
  kind: AssetKind;
  /** The original name of the file when uploaded/created */
  originalFilename: string;
  /** The MIME type (e.g., 'application/pdf') */
  contentType: string;
  /** File size in bytes */
  size: number;
  /** Document creation timestamp */
  createdAt: Date;
  /** Document update timestamp */
  updatedAt: Date;
}

const AssetSchema = new Schema<IAsset>(
  {
    owner: { type: Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    project: { type: Schema.Types.ObjectId, ref: 'Project', index: true },
    key: { type: String, required: true, unique: true },
    kind: {
      type: String,
      enum: ['template', 'source', 'export-docx', 'export-pdf'],
      required: true,
      index: true,
    },
    originalFilename: { type: String, required: true },
    contentType: { type: String, required: true },
    size: { type: Number, required: true, min: 0 },
  },
  { timestamps: true }
);

// High-performance indexes for dashboard fetching and project-level queries
AssetSchema.index({ owner: 1, createdAt: -1 });
AssetSchema.index({ project: 1, kind: 1, createdAt: -1 });

export const Asset = mongoose.model<IAsset>('Asset', AssetSchema);