import crypto from 'node:crypto';
import mongoose from 'mongoose';
import { env } from '../../../core/config/env.ts'; // Adjust path
import { PaymentWebhookEvent } from '../models/PaymentWebhook.model.ts';
import { PaymentOrder } from '../models/PaymentOrder.model.ts';
import { changeUserPlan } from './subscription.service.ts';
import { createLogger } from '../../../core/lib/logger.ts';

const log = createLogger('payment-webhook-service');

/**
 * @function verifyWebhookSignature
 * @description Cryptographically verifies that the incoming webhook is genuinely from Razorpay.
 * Uses raw Buffer to prevent Express JSON parser mutation issues.
 *
 * @param {Buffer} payload - The raw request body buffer.
 * @param {string} signature - The `x-razorpay-signature` header.
 * @returns {boolean} True if authentic.
 */
export function verifyWebhookSignature(
  payload: Buffer,
  signature: string
): boolean {
  try {
    const expectedSignature = crypto
      .createHmac('sha256', env.PAYMENT_WEBHOOK_SECRET!) // Ensure this is the Webhook Secret, not the Key Secret
      .update(payload)
      .digest('hex');

    const expectedBuffer = Buffer.from(expectedSignature);
    const receivedBuffer = Buffer.from(signature);

    if (expectedBuffer.length !== receivedBuffer.length) {
      return false;
    }

    return crypto.timingSafeEqual(expectedBuffer, receivedBuffer);
  } catch (err) {
    log.error({ err }, 'Webhook signature verification threw an error');
    return false;
  }
}

/**
 * @function hashPayload
 * @description Hashes the raw payload to store in the database for audit trails and duplicate detection.
 *
 * @param {Buffer} payload - The raw request body buffer.
 * @returns {string} The SHA-256 hash of the payload.
 */
export function hashPayload(payload: Buffer): string {
  return crypto.createHash('sha256').update(payload).digest('hex');
}

/**
 * @function processRazorpayWebhook
 * @description The core engine for handling webhooks. Ensures idempotency, updates the order, and grants the subscription.
 *
 * @param {any} parsedBody - The parsed JSON body from Razorpay.
 * @param {string} payloadHash - The hash generated by `hashPayload`.
 */
export async function processRazorpayWebhook(
  parsedBody: unknown,
  payloadHash: string
): Promise<void> {
  const body = (parsedBody ?? {}) as Record<string, any>;
  const providerEventId = body.id;
  const eventType = body.event;

  // 1. Idempotency Check: Did we already process this exact webhook?
  const existingEvent = await PaymentWebhookEvent.findOne({ providerEventId });
  if (existingEvent && existingEvent.status === 'processed') {
    log.info({ providerEventId }, 'Webhook already processed, skipping.');
    return;
  }

  const mongoSession = await mongoose.startSession();

  try {
    await mongoSession.withTransaction(async () => {
      // 2. Log the webhook receipt
      const webhookDoc = await PaymentWebhookEvent.findOneAndUpdate(
        { providerEventId },
        {
          provider: 'razorpay',
          providerEventId,
          eventType,
          payloadHash,
          status: 'received',
        },
        { upsert: true, new: true, session: mongoSession }
      );

      // 3. Process the 'order.paid' event (Razorpay confirms the money is secure)
      if (eventType === 'order.paid') {
        const orderPayload = body.payload?.order?.entity;
        const razorpayOrderId = orderPayload?.id;
        const paymentId = body.payload?.payment?.entity?.id || 'unknown';

        // Find our internal pending order
        const order = await PaymentOrder.findOne({
          razorpayOrderId,
          status: { $ne: 'paid' }, // Prevent double-upgrading if manually processed earlier
        }).session(mongoSession);

        if (order) {
          // Update Order Status
          order.status = 'paid';
          order.razorpayPaymentId = paymentId;
          order.planGrantedAt = new Date();
          await order.save({ session: mongoSession });

          // Grant the Subscription Tier
          await changeUserPlan(
            order.user,
            order.planPurchased,
            'upgrade',
            paymentId,
            mongoSession,
            order.purpose
          );
        } else {
          log.warn(
            { razorpayOrderId },
            'Paid webhook received for unknown or already paid order'
          );
        }
      } else if (eventType === 'payment.failed') {
        const razorpayOrderId = body.payload?.payment?.entity?.order_id;
        if (razorpayOrderId) {
          await PaymentOrder.updateOne(
            { razorpayOrderId, status: { $ne: 'paid' } },
            { $set: { status: 'failed' } },
            { session: mongoSession }
          );
          log.info({ razorpayOrderId }, 'Marked order as failed due to payment.failed webhook');
        }
      }

      // 4. Mark the webhook as successfully processed
      webhookDoc.status = 'processed';
      await webhookDoc.save({ session: mongoSession });
    });
  } catch (err) {
    log.error({ err, providerEventId }, 'Failed to process webhook event');

    // Attempt to save the failure state outside the aborted transaction
    await PaymentWebhookEvent.updateOne(
      { providerEventId },
      { $set: { status: 'failed', error: (err as Error).message } }
    ).catch((e) => log.error({ e }, 'Failed to update webhook failure status'));

    throw err; // Re-throw so the controller can send a 500 back to Razorpay to trigger a retry
  } finally {
    await mongoSession.endSession();
  }
}
