import mongoose, { Schema, Document } from 'mongoose';

/**
 * @interface IPaymentOrder
 * @extends {Document}
 * @description Represents a transactional payment order for upgrading or purchasing subscription tiers.
 */
export interface IPaymentOrder extends Document {
  /** Reference to the User initiating the payment */
  user: mongoose.Types.ObjectId;
  /** Payment gateway provider (currently Razorpay) */
  provider: 'razorpay';
  /** External order ID generated by Razorpay */
  razorpayOrderId: string;
  /** External payment ID generated upon successful Razorpay capture */
  razorpayPaymentId?: string;
  /** Transaction amount in the smallest currency unit (e.g., paise for INR) */
  amount: number;
  /** Currency code (e.g., 'INR') */
  currency: string;
  /** Purpose of the payment (e.g., 'Subscription Purchase') */
  purpose: string;
  /** Current lifecycle status of the payment order */
  status: 'created' | 'pending' | 'paid' | 'failed' | 'cancelled' | 'refunded';
  /** Unique key to prevent duplicate processing of the exact same transaction */
  idempotencyKey: string;
  /** The specific subscription tier the user is attempting to purchase */
  planPurchased: 'none' | 'normal' | 'pro' | 'premium';
  /** Timestamp recording exactly when the plan was successfully applied to the user's account */
  planGrantedAt?: Date;
  /** Document creation timestamp */
  createdAt: Date;
  /** Document update timestamp */
  updatedAt: Date;
}

const paymentOrderSchema = new Schema<IPaymentOrder>(
  {
    user: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    provider: {
      type: String,
      default: 'razorpay',
    },
    razorpayOrderId: {
      type: String,
      required: true,
      unique: true,
    },
    razorpayPaymentId: String,
    amount: {
      type: Number,
      required: true,
    },
    currency: {
      type: String,
      required: true,
    },
    purpose: {
      type: String,
      required: true,
    },
    status: {
      type: String,
      enum: ['created', 'pending', 'paid', 'failed', 'cancelled', 'refunded'],
      default: 'created',
    },
    idempotencyKey: {
      type: String,
      unique: true,
      required: true,
    },
    planPurchased: {
      type: String,
      enum: ['none', 'normal', 'pro', 'premium'],
      required: true,
    },
    planGrantedAt: Date,
  },
  {
    timestamps: true,
  }
);

// Compound index for authenticated order history and status lookups
paymentOrderSchema.index({ user: 1, status: 1 });

export const PaymentOrder = mongoose.model<IPaymentOrder>(
  'PaymentOrder',
  paymentOrderSchema
);
